// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1
tclmode
set env(RC_VERSION) "v11.20-s017_1"
vpxmode
set dofile abort exit
usage -auto
set log file fv/dct4_par_2d/rtl_to_g1_withoutovf.log -replace
// tclmode
// set env(CDN_SYNTH_ROOT) /home/cadence_tools/cadence/ET12.10.101_lnx86/tools.lnx86
// vpxmode
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set undriven signal Z -golden

add search path -library /root/cadence_db/cadence_library
read library -statetable -liberty -pg_pin -both  \
	tcbn45gsbwpbc0d88_ccs.lib

add search path -design /root/Desktop/RRP/dct4_par_2d
read design  -verilog -define SYNTHESIS  -golden -lastmod -noelab \
	/root/Desktop/RRP/dct4_par_2d/dct4_par_2d.v \
	/root/Desktop/RRP/dct4_par_2d/dct_4.v \
	/root/Desktop/RRP/dct4_par_2d/float_adder.v \
	/root/Desktop/RRP/dct4_par_2d/wallacer2.v \
	/root/Desktop/RRP/dct4_par_2d/fulladd.v \
	/root/Desktop/RRP/dct4_par_2d/halfadd.v \
	/root/Desktop/RRP/dct4_par_2d/recurse40.v \
	/root/Desktop/RRP/dct4_par_2d/recurse.v \
	/root/Desktop/RRP/dct4_par_2d/recurse8.v \
	/root/Desktop/RRP/dct4_par_2d/kgp.v \
	/root/Desktop/RRP/dct4_par_2d/kgp_carry.v \
	/root/Desktop/RRP/dct4_par_2d/recursive_stage1.v

elaborate design -golden -root dct4_par_2d

read design -verilog -revised -lastmod -noelab \
	-unzip fv/dct4_par_2d/g1.v.gz

elaborate design -revised -root dct4_par_2d

substitute blackbox model -golden
report design data
report black box

uniquify -all -nolib
set flatten model -latch_transparent
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
// set parallel option -threads 4 -license xl
set analyze option -auto

write hier_compare dofile fv/dct4_par_2d/hier_rtl_to_g1_withoutovf.do \
	-noexact_pin_match -constraint -usage -replace -run_hier \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath -verbose"
run hier_compare fv/dct4_par_2d/hier_rtl_to_g1_withoutovf.do
usage
// report hier_compare result -flattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -diff -count]"
if {[get_compare_points -diff -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -diff] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
